<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>peopleBox_CCField</name>
   <tag></tag>
   <elementGuidId>0d893357-2807-4b2f-96dd-6819d6db6c58</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-untouched ng-valid</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>Cc</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hidePeopleBoxOnInit&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12 col-md-4&quot;]/div[@class=&quot;row pad&quot;]/div[@class=&quot;col-xs-7 col-md-9 col-lg-9&quot;]/textarea[@class=&quot;form-control ng-pristine ng-untouched ng-valid&quot;]</value>
   </webElementProperties>
</WebElementEntity>
